apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kiosks.kiosk.openshift.io
spec:
  group: kiosk.openshift.io
  names:
    kind: Kiosk
    listKind: KioskList
    plural: kiosks
    singular: kiosk
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
